# Generated by Django 4.2.13 on 2025-01-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderserviceapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждение по email'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='remainingstock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
    ]
