# Generated by Django 4.2.13 on 2025-01-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderserviceapi', '0002_buyer_is_verified_alter_buyer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(default=20, verbose_name='возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='фамилия'),
        ),
    ]
