# Generated by Django 4.2.13 on 2025-01-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderserviceapi', '0002_alter_buyer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='building',
            field=models.IntegerField(verbose_name='здание'),
        ),
    ]
