# Generated by Django 4.2.13 on 2025-01-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderserviceapi', '0003_buyer_age_alter_buyer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='возраст'),
        ),
    ]
